name: C/C++ CI

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'LICENSE.md'
    branches: [ master, master-ci]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Load Modules
      shell: bash
      run: |
        module load gflags-2.1.2-gcc-7.4.0-4vasfdn 
        module load intel-tbb-2020.2-gcc-7.4.0-tpthcp6
        module load boost-1.72.0-gcc-7.4.0-mfchp2d
        module load llvm-openmp-romp-mod-gcc-7.4.0-6kbf57l 
        module load dyninst-10.1.2-gcc-7.4.0-pxqjj4q

     - name: Build make files
       shell: bash
       run: |
         module load gcc-7.4.0-gcc-7.5.0-domzzsx
         mkdir build
         mkdir install
         cd build 
         cmake -DCMAKE_CXX_FLAGS=-std=c++17
               -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
               -DCMAKE_INSTALL_PREFIX=`pwd`/../install ..
    - name: Build and install
      run: make install
      working-directory: ./build
